### ISSUE TITLE
Est-ce qu'il ne serait pas plus intéressant d'intervertir `m` et `v` ?

### ISSUE THREAD

**Issue by pierre-eliep-met** [adrienm7/hypertexte#2]
Bonjour bonjour :)
Le `m` est sur la dernière ligne de lettres, et il vient souvent avec le `p` (amp.., emp...), donc il faut passer de la première ligne à la troisième (ce que le développeur d'optimot appelle " croisements " je crois). 
Or le `v` est juste au dessus du `m`, et n'a pas de roulement avec les lettres à côté, de même que `mc`, `mk` ne semblent pas très courants.
-> pourquoi ne pas les intervertir ?

**Comment by adrienm7** [comment]
Hello, c’est bien, je vois que tu essayes la disposition 😀
Si tu veux échanger, n’hésite pas. Tu es sur Discord ? Comment as-tu découvert HyperTexte ?

Le `M` et le `V` sont à leur place respective, car sur les claviers décalés (≈95% des claviers donc) la touche `N` en AZERTY (qui est `M` en HyperTexte) est quasiment aussi confortable que la touche directement sous la homerow. À noter que c’est exactement pareil pour l’index gauche, le `J` et le `,` sont tous deux très bien placés.

L'arrangement actuel met donc le `M`, qui est environ 2 fois plus fréquent que le `V`, à une meilleure position. Cela réduit le nombre d'extensions latérales pour déplacer l'index droit d'une colonne à gauche. Pour taper le `M` en HyperTexte, le décalage vers la gauche n’est que de ½ touche vs 1 touche pour le `V`.

Le `P` étant justement 3 colonnes plus à droite, l’arrangement actuel est même plus confortable pour écrire le bigramme `MP`. En effet, l'index n’a pas à se décaler d’une colonne à gauche, incitant à bouger vers la gauche le reste de la main, alors que l’annulaire droit doit encore ensuite se lever sur sa colonne pour taper `P`.

Tu peux très bien intervertir si c’est ce que tu trouves plus confortable. Cela n’impactera pas le nombre de SFBs vu que ces deux touches sont à taper du même doigt. Mais même sur clavier orthogonal, la position actuelle du `M` est sans doute la mieux. Ou alors éventuellement échager plutôt `D` et `M`, mais `D` ayant une fréquence encore plus élevée, elle mérite de ne pas faire de déplacement à gauche, même de seulement ½ u (taille d’une touche).

**Comment by pierre-eliep-met** [comment]
Hello ! Merci de la proposition, mais non je ne suis pas sur discord :/
J'avais découvert hypertexte par [cet article](https://bepo.fr/wiki/Utilisateur:Adrien_Moyaux) du site bépo que tu avais écrit, en cherchant des truc sur optimot.
Ok, merci très clair ! je verrai si je change quelque chose, il faut déjà que je continue d'apprendre la disposition ;)
